// <auto-generated />
namespace CEvery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AutoGenAppNoRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AutoGenAppNoRename));
        
        string IMigrationMetadata.Id
        {
            get { return "201408101548255_AutoGenAppNoRename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
