// <auto-generated />
namespace CEvery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class RTBNotMandatory_QuoteDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RTBNotMandatory_QuoteDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201408151518346_RTBNotMandatory_QuoteDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
